version: "3.0"
services:
  jekins:
    container_name: jenkins-container
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jekins-volume:/docker/jekins
volumes:
    jekins-volume:
        external: false